export const addNote = async () => {
  try {
  } catch (err) {
    console.error(err.message);
  }
};
